/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Classes.CPU;
import Classes.DefinicoesDeImagem;
import Classes.Player;
import java.util.HashSet;
import java.util.Random;
import java.util.Set;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author William
 */
public class Confronto extends javax.swing.JFrame {
DefinicoesDeImagem defImg = new DefinicoesDeImagem();
CPU cpu = new CPU();
Player player = new Player();
Random random = new Random();
String caminho = "";
String selecionado;
int pontosPlayer = 0;
int pontosCPU = 0;
    /**
     * Creates new form Confronto
     */
    public Confronto() {
        initComponents();
        alinharPainel();
        definirTodasImagens();
    }

    public void alinharPainel(){
        Painel.setAlignmentX(PainelFundo.getWidth()/2);
        Painel.setAlignmentY(0);
        CPU.setSize(Painel.getHeight(), CPU.getWidth());
        Player.setSize(Painel.getHeight(), Player.getWidth());
        VS.setSize(Painel.getHeight(), VS.getWidth());
    }
    

    
    public void definirTodasImagens(){
        caminho = "C:\\Users\\William\\Desktop\\IFSP\\2 Semestre\\LP2 - Linguagem de Programação 2\\Programas em Java\\Jokenpo\\src\\Imagens\\Papel.png";
        defImg.escalonarImagemBTN(caminho, Papel);
        caminho = "C:\\Users\\William\\Desktop\\IFSP\\2 Semestre\\LP2 - Linguagem de Programação 2\\Programas em Java\\Jokenpo\\src\\Imagens\\Pedra.png";
        defImg.escalonarImagemBTN(caminho, Pedra);
        caminho = "C:\\Users\\William\\Desktop\\IFSP\\2 Semestre\\LP2 - Linguagem de Programação 2\\Programas em Java\\Jokenpo\\src\\Imagens\\Tesoura.png";
        defImg.escalonarImagemBTN(caminho, Tesoura);
    }
    public void jogar(String caminho){
        defImg.escalonarImagem(caminho, Player);
        defImg.escalonarImagem(cpu.defCPU(caminho), CPU);
        Player.setText("");
        CPU.setText("");
    }
    public void regraGame(Player player, CPU cpu){
        if(player.getPlayerHand() == "Pedra"){
            if(cpu.getCpuHand() == "Pedra"){
                System.out.println("Empate");
            }
            else if(cpu.getCpuHand() == "Papel"){
                pontosCPU++;
            }
            else if(cpu.getCpuHand() == "Tesoura"){
                pontosPlayer++;
            }
        }
        else if(player.getPlayerHand() == "Papel"){
            if(cpu.getCpuHand() == "Pedra"){
                pontosPlayer++;
            }
            else if(cpu.getCpuHand() == "Papel"){
                System.out.println("Empate");
            }
            else if(cpu.getCpuHand() == "Tesoura"){
                pontosCPU++;
            }
        }
        else if(player.getPlayerHand() == "Tesoura"){
            if(cpu.getCpuHand() == "Pedra"){
                pontosCPU++;
            }
            else if(cpu.getCpuHand() == "Papel"){
                pontosPlayer++;
            }
            else if(cpu.getCpuHand() == "Tesoura"){
                System.out.println("Empate");
            }
        }
    }
    public void setAllText(){
        PPlayer.setText("Player\n " + (Integer.toString(pontosPlayer)));
        PCPU.setText("CPU\n " + (Integer.toString(pontosCPU)));
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelFundo = new javax.swing.JPanel();
        Painel = new javax.swing.JPanel();
        CPU = new javax.swing.JLabel();
        Player = new javax.swing.JLabel();
        VS = new javax.swing.JLabel();
        PPlayer = new javax.swing.JLabel();
        PCPU = new javax.swing.JLabel();
        Pedra = new javax.swing.JButton();
        Papel = new javax.swing.JButton();
        Tesoura = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PainelFundo.setAlignmentX(0.0F);

        CPU.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        CPU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CPU.setText("?");
        CPU.setAlignmentX(1.0F);
        CPU.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Player.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        Player.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Player.setText("?");
        Player.setAlignmentX(1.0F);
        Player.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        VS.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        VS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VS.setText("VS");

        PPlayer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PPlayer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PPlayer.setText("0");

        PCPU.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PCPU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PCPU.setText("0");

        javax.swing.GroupLayout PainelLayout = new javax.swing.GroupLayout(Painel);
        Painel.setLayout(PainelLayout);
        PainelLayout.setHorizontalGroup(
            PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Player, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(VS, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(PPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PCPU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(124, 124, 124)
                .addComponent(CPU, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PainelLayout.setVerticalGroup(
            PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CPU, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(PainelLayout.createSequentialGroup()
                            .addComponent(PPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(VS, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(PCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Player, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        Pedra.setAlignmentX(1.0F);
        Pedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PedraActionPerformed(evt);
            }
        });

        Papel.setAlignmentX(1.0F);
        Papel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PapelActionPerformed(evt);
            }
        });

        Tesoura.setAlignmentX(1.0F);
        Tesoura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TesouraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelFundoLayout = new javax.swing.GroupLayout(PainelFundo);
        PainelFundo.setLayout(PainelFundoLayout);
        PainelFundoLayout.setHorizontalGroup(
            PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PainelFundoLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(Pedra, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Papel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tesoura, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PainelFundoLayout.setVerticalGroup(
            PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelFundoLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(Painel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Pedra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Papel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Tesoura, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PainelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PedraActionPerformed
        player.setPlayerHand("Pedra");
        caminho = "C:\\Users\\William\\Desktop\\IFSP\\2 Semestre\\LP2 - Linguagem de Programação 2\\Programas em Java\\Jokenpo\\src\\Imagens\\Pedra.png";
        jogar(caminho);
        System.out.println(cpu.getNumMao());
        System.out.println(caminho);
        regraGame(player, cpu);
        System.out.println("CPU ESCOLHA " + cpu.getCpuHand());
        setAllText();
    }//GEN-LAST:event_PedraActionPerformed

    private void PapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PapelActionPerformed
        player.setPlayerHand("Papel");
        caminho = "C:\\Users\\William\\Desktop\\IFSP\\2 Semestre\\LP2 - Linguagem de Programação 2\\Programas em Java\\Jokenpo\\src\\Imagens\\Papel.png";
        jogar(caminho);
        System.out.println(cpu.getNumMao());
        System.out.println(caminho);
        regraGame(player, cpu);
        setAllText();
    }//GEN-LAST:event_PapelActionPerformed

    private void TesouraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TesouraActionPerformed
       player.setPlayerHand("Tesoura");
       caminho = "C:\\Users\\William\\Desktop\\IFSP\\2 Semestre\\LP2 - Linguagem de Programação 2\\Programas em Java\\Jokenpo\\src\\Imagens\\Tesoura.png";
       jogar(caminho);
       System.out.println(cpu.getNumMao());
       System.out.println(caminho);
       regraGame(player, cpu);
       setAllText();
    }//GEN-LAST:event_TesouraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Confronto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Confronto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Confronto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Confronto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Confronto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CPU;
    private javax.swing.JLabel PCPU;
    private javax.swing.JLabel PPlayer;
    private javax.swing.JPanel Painel;
    private javax.swing.JPanel PainelFundo;
    private javax.swing.JButton Papel;
    private javax.swing.JButton Pedra;
    private javax.swing.JLabel Player;
    private javax.swing.JButton Tesoura;
    private javax.swing.JLabel VS;
    // End of variables declaration//GEN-END:variables
}
